"""agregar opponent_cfn_id a cfn_matches

Revision ID: 1cdbf8d969af
Revises: 7c5f6a96e296
Create Date: 2026-08-19 20:55:51.894913

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1cdbf8d969af"
down_revision: Union[str, None] = "7c5f6a96e296"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cfn_matches", sa.Column("opponent_cfn_id", sa.String(), nullable=True)
    )
    op.create_index(
        op.f("ix_cfn_matches_opponent_cfn_id"),
        "cfn_matches",
        ["opponent_cfn_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cfn_matches_opponent_cfn_id"), table_name="cfn_matches")
    op.drop_column("cfn_matches", "opponent_cfn_id")
    # ### end Alembic commands ###
