"""tier_lists usa template_id en vez de game

Revision ID: 227b75ca4a41
Revises: 6fabf4a777b2
Create Date: 2026-08-17 02:45:55.500316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '227b75ca4a41'
down_revision: Union[str, None] = '6fabf4a777b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tier_lists', sa.Column('template_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tier_lists', 'tier_list_templates', ['template_id'], ['id'])
    op.drop_column('tier_lists', 'game')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tier_lists', sa.Column('game', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tier_lists', type_='foreignkey')
    op.drop_column('tier_lists', 'template_id')
    # ### end Alembic commands ###
