"""agregar card_background_brightness a cfn_registrations

Revision ID: 4745bf67fa9e
Revises: dcd9c0ea243a
Create Date: 2026-08-20 21:12:15.013238

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4745bf67fa9e"
down_revision: Union[str, None] = "dcd9c0ea243a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cfn_registrations",
        sa.Column("card_background_brightness", sa.Float(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cfn_registrations", "card_background_brightness")
    # ### end Alembic commands ###
