"""agregar tier_lists

Revision ID: 7535b529f0a4
Revises: 887a51227cfc
Create Date: 2026-08-17 01:39:17.354065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7535b529f0a4'
down_revision: Union[str, None] = '887a51227cfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tier_lists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game', sa.String(), nullable=False),
    sa.Column('tiers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tier_lists')
    # ### end Alembic commands ###
