"""agregar label_width a tier_lists

Revision ID: 7c5f6a96e296
Revises: 671da9804f4c
Create Date: 2026-08-19 20:07:40.023932

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7c5f6a96e296"
down_revision: Union[str, None] = "671da9804f4c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tier_lists", sa.Column("label_width", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tier_lists", "label_width")
    # ### end Alembic commands ###
