"""agregar cfn_profiles

Revision ID: 854dd6be67a5
Revises: c7fff241f52a
Create Date: 2026-08-10 23:26:47.459653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '854dd6be67a5'
down_revision: Union[str, None] = 'c7fff241f52a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cfn_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cfn_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('league_rank', sa.String(), nullable=True),
    sa.Column('league_points', sa.Integer(), nullable=True),
    sa.Column('master_rating', sa.Integer(), nullable=True),
    sa.Column('character_name', sa.String(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cfn_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cfn_profiles')
    # ### end Alembic commands ###
