"""agregar cfn_matches

Revision ID: 887a51227cfc
Revises: 854dd6be67a5
Create Date: 2026-08-14 23:21:31.027498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '887a51227cfc'
down_revision: Union[str, None] = '854dd6be67a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cfn_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cfn_id', sa.String(), nullable=False),
    sa.Column('character_name', sa.String(), nullable=True),
    sa.Column('opponent_name', sa.String(), nullable=True),
    sa.Column('opponent_character', sa.String(), nullable=True),
    sa.Column('won', sa.Boolean(), nullable=True),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cfn_id'], ['cfn_profiles.cfn_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cfn_id', 'played_at', 'opponent_name', name='uq_cfn_match')
    )
    op.create_index(op.f('ix_cfn_matches_cfn_id'), 'cfn_matches', ['cfn_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cfn_matches_cfn_id'), table_name='cfn_matches')
    op.drop_table('cfn_matches')
    # ### end Alembic commands ###
