"""agregar sf6_meta_snapshots

Revision ID: ccfb927612e1
Revises: d6557e49d4a9
Create Date: 2026-08-21 01:53:12.134699

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ccfb927612e1"
down_revision: Union[str, None] = "d6557e49d4a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sf6_meta_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("snapshot_type", sa.String(), nullable=False),
        sa.Column("month", sa.String(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("snapshot_type", "month"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sf6_meta_snapshots")
    # ### end Alembic commands ###
