"""agregar campos de records a cfn_profiles

Revision ID: d6557e49d4a9
Revises: 4745bf67fa9e
Create Date: 2026-08-21 01:11:17.098831

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d6557e49d4a9"
down_revision: Union[str, None] = "4745bf67fa9e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cfn_profiles", sa.Column("drive_impact_received", sa.Float(), nullable=True)
    )
    op.add_column(
        "cfn_profiles", sa.Column("drive_parry_perfect", sa.Float(), nullable=True)
    )
    op.add_column(
        "cfn_profiles",
        sa.Column("drive_impact_punish_landed", sa.Float(), nullable=True),
    )
    op.add_column(
        "cfn_profiles", sa.Column("corner_time_opponent", sa.Float(), nullable=True)
    )
    op.add_column("cfn_profiles", sa.Column("throws_landed", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cfn_profiles", "throws_landed")
    op.drop_column("cfn_profiles", "corner_time_opponent")
    op.drop_column("cfn_profiles", "drive_impact_punish_landed")
    op.drop_column("cfn_profiles", "drive_parry_perfect")
    op.drop_column("cfn_profiles", "drive_impact_received")
    # ### end Alembic commands ###
