"""agregar card_background_url a cfn_registrations

Revision ID: dcd9c0ea243a
Revises: b7e7dd7cf3e5
Create Date: 2026-08-20 03:22:06.406742

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dcd9c0ea243a"
down_revision: Union[str, None] = "b7e7dd7cf3e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cfn_registrations",
        sa.Column("card_background_url", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cfn_registrations", "card_background_url")
    # ### end Alembic commands ###
